fix for starting linuxcncrsh

diff --git a/scripts/linuxcnc.in b/scripts/linuxcnc.in
--- a/scripts/linuxcnc.in
+++ b/scripts/linuxcnc.in
@@ -883,6 +883,16 @@ case $EMCDISPLAY in
     fi
     result=$?
   ;;
+  linuxcncrsh)
+    # all other displays are assumed to be commands on the PATH
+    if ! program_available $EMCDISPLAY; then
+        echo "Can't execute DISPLAY program $EMCDISPLAY $EMCDISPLAYARGS $EXTRA_ARGS"
+        Cleanup
+        exit 1
+    fi
+    $EMCDISPLAY -- -ini "$INIFILE" $EMCDISPLAYARGS $EXTRA_ARGS
+    result=$?
+  ;;
   *)
     # all other displays are assumed to be commands on the PATH
     if ! program_available $EMCDISPLAY; then
